let allSubjects = [
    {
      id: 1001,
      imgALT: "Math img",
      imgSRC: "img/math.png",
      iconSRC: "fa-solid fa-calculator",
      name: "Math",
      location: "London",
      price: 100,
      spaces: 10,
    },
    {
      id: 1002,
      imgALT: "Music img",
      imgSRC: "img/music.png",
      iconSRC: 'fa-solid fa-music',
      name: "Music",
      location: "London",
      price: 150,
      spaces: 8,
    },
    {
      id: 1003,
      imgALT: "English img",
      imgSRC: "img/language.png",
      iconSRC: "fa-solid fa-book-atlas",
      name: "English",
      location: "London",
      price: 120,
      spaces: 8,
    },
    {
      id: 1004,
      imgALT: "Math img",
      imgSRC: "img/math.png",
      iconSRC: "fa-solid fa-calculator",
      name: "Math",
      location: "Brighton",
      price: 120,
      spaces: 8,
    },
    {
      id: 1005,
      imgALT: "Natural Sciences img",
      imgSRC: "img/plant.png",
      iconSRC: "fa-solid fa-seedling",
      name: "Natural Sciences",
      location: "York",
      price: 80,
      spaces: 15,
    },
    {
      id: 1006,
      imgALT: "History img",
      imgSRC: "img/history.png",
      iconSRC: "fa-solid fa-book",
      name: "History",
      location: "London",
      price: 30,
      spaces: 5,
    },
    {
      id: 1007,
      imgALT: "Music img",
      imgSRC: "img/music.png",
      iconSRC: 'fa-solid fa-music',
      name: "Music",
      location: "Manchester",
      price: 130,
      spaces: 12,
    },
    {
      id: 1008,
      imgALT: "History img",
      imgSRC: "img/history.png",
      iconSRC: "fa-solid fa-book",
      name: "History",
      location: "Bristol",
      price: 50,
      spaces: 9,
    },
    {
      id: 1009,
      imgALT: "physics img",
      imgSRC: "img/physics.png",
      iconSRC: "fa-solid fa-atom",
      name: "Physics",
      location: "Bristol",
      price: 50,
      spaces: 9,
    },
    {
      id: 1010,
      imgALT: "Spanish img",
      imgSRC: "img/language.png",
      iconSRC: "fa-solid fa-book-atlas",
      name: "Spanish",
      location: "London",
      price: 100,
      spaces: 40,
    },
];