let allSubjects = [
    {
      id: 1001,
      imgALT: "Math img",
      imgSRC: "math.png",
      name: "Math",
      location: "London",
      price: 100,
      spaces: 10,
      maxspaces: 10,
    },
    {
      id: 1002,
      imgALT: "Math img",
      imgSRC: "math.png",
      name: "Music",
      location: "London",
      price: 150,
      spaces: 8,
      maxspaces: 8,
    },
    {
      id: 1003,
      imgALT: "Math img",
      imgSRC: "math.png",
      name: "English",
      location: "London",
      price: 120,
      spaces: 8,
      maxspaces: 8,
    },
    {
      id: 1003,
      imgALT: "Math img",
      imgSRC: "math.png",
      name: "Math",
      location: "Brighton",
      price: 120,
      spaces: 8,
      maxspaces: 8,
    },
];